### ISSUE TITLE
Enhancements required for 'Graphic Designing Section'

### ISSUE THREAD

**Issue by saloni-garg** [saloni-garg/saloni-garg.github.io#1]
The posters in "Graphic Designing Projects" don't open separately. Like when you click on the bunch of expanded pictures, one of them will open up, irrespective of the position of pointer while clicking.

This can be better understood when you've got the "Graphic Designing Projects" section of website opened in the other tab. https://saloni-garg.github.io

**Comment by maridilip** [comment]
can u elaborate on this ? what do u mean by dont open singly?

**Comment by saloni-garg** [comment]
I've updated the comment. Please have a look :)
